#$schema: https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sander-cool-app2-acr
  tags:
    - helm
spec:
  type: config-repo
  lifecycle: development
  owner: demo-team
  dependsOn:
    - component:default/sander-cool-app2